name: gh-pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Generate .env file
        run: |
          touch ./assets/.env
          echo "CHECK=${{ secrets.CHECK }}" >> ./assets/.env

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /hayat_onldocc_rule/
